<!DOCTYPE html>
<html>
<head>
  <title>Meine Seite</title>
  <style>
    /* Stil für den Header */
    header {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
    }
    
    /* Stil für den Footer */
    footer {
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
    }
    
    /* Stil für den Inhalt */
    main {
      margin-top: 80px;
      margin-bottom: 80px;
      height: 100%;
      overflow-y: scroll;
      padding: 20px;
    }
  </style>
</head>
<body>
    <header>
        <?php   
            include_once('navbar.php');
        ?>
    </header>
  
    <main>
        <!-- Hier kommt der Inhalt der Seite hin -->
        <h2>Willkommen auf meiner Seite!</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Etiam imperdiet semper sapien, vitae varius sapien lacinia quis. Sed at ipsum quis neque ornare semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hendrerit, augue eget bibendum sollicitudin, nisi ipsum congue felis, vel vestibulum ante sapi
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed neque ligula. Nulla facilisi. Fusce porttitor pretium diam, sit amet efficitur lectus vestibulum vel. Suspendisse eget magna eu augue pharetra sodales. Mauris eu lorem sit amet felis ultrices rutrum sed eget purus. Sed eget neque sed lacus ultricies vestibulum. Sed non odio at nibh feugiat malesuada. Sed euismod tortor eget nunc vulputate euismod.</p>
        <p>Donec facilisis odio at libero faucibus, in tincidunt nunc blandit. Integer sed lacus sodales, congue magna vel, efficitur dolor. Nulla facilisi. Sed ac luctus enim. Proin dictum diam vel eleifend hendrerit. Praesent id lectus ut felis rutrum facilisis. Vivamus efficitur sit amet lectus eget volutpat. Integer sed tortor vel ex sodales venenatis ac at orci. Curabitur tincidunt magna et diam bibendum varius. Suspendisse ullamcorper lectus a orci facilisis, at dignissim metus eleifend. Nam vel efficitur nunc. Donec eu enim vitae lacus porttitor gravida.</p>
        <p>Suspendisse non semper nisl. Duis ullamcorper urna eget risus molestie, ut dignissim nibh malesuada. Suspendisse ut bibendum ex. Praesent auctor tortor ut augue interdum imperdiet. Proin sed aliquet ante. Duis pulvinar felis non sapien mattis blandit. Praesent maximus nulla in congue tincidunt. Vestibulum bibendum eros vel tempor vulputate.</p>
    </main>
    <footer>
        <?php   
            include_once('footer.php');
        ?>
    </footer>
<body>